version: '2'
services:
  php-fpm:
    build:
      context: php-fpm
    volumes:
      - ./../application:/var/www/coding-test
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
  nginx:
    build:
      context: nginx
      args:
        - PHP_UPSTREAM_CONTAINER=php-fpm
        - PHP_UPSTREAM_PORT=9000
    volumes_from:
      - php-fpm
    volumes:
      - ./logs:/var/log/nginx
      - ./nginx/sites:/etc/nginx/sites-available
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    depends_on:
      - php-fpm